# Generated by Django 6.0.1 on 2026-01-17 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0002_alter_category_options_cart_menuitem_cartitem_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(2.0)],
            ),
        ),
    ]
